course = "  Python Programming  "
print(course.upper())
print(course.lower())
print(course.title())
# print(course.strip())
print(course.rstrip())
print(course.lstrip())
print(course.find("gram"))
print(course.find("Gram"))
print(course.replace("P", "s"))
print("Pro" in course)
print("swift" not in course)
